layout_spectrum: 0.6098567559374588
typography_spectrum: 0.5575952128004652
color:
  brandStrength: 0.0464986819161637
  lightness: 0.1270713732557574
  saturation: 0.10331092187166584
  rhythmicContrast: 0.18662501314470525
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e298f4a-23fd-424d-85f3-ff25c48fa4c8.png
name: Agencija Connect
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Portfolio
    id: 57e6afcb-e469-49c7-9d3e-8457e96f582c
    type: content
  - name: Cjenik
    url: >-
      https://docs.google.com/forms/d/e/1FAIpQLScdOVsi3x4G0Lhj3_OM6jahpukJaGd1BQo7SdDcZ_cg58LITg/viewform
    type: external
  - name: Kontakt
    id: a50ff2fa-b95e-4687-b31c-a102b3e1e8e7
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d3c549c9-bef1-4fa3-a40e-b47af7508b69.png
title: Agencija Connect
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2Fvideoseries%3Flist%3DPL1yyP-uh7GHBhZ-hIQ8LfdEBA5QAG6OD7&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DhaFprGMrIys&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FhaFprGMrIys%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: hong thuong HD
          url: 'https://www.youtube.com/user/styleproshoworg'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://www.youtube.com/favicon.ico'
        domain: youtu.be
      keywords: []
      description: >-
        Note: this website will bring to you: multi-graphic, multimedia (all are
        free): http://freemultimedia.vn/
      '@type': VideoObject
      app_links: []
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/haFprGMrIys?list=PL1yyP-uh7GHBhZ-hIQ8LfdEBA5QAG6OD7'
      title: >-
        Video Background HD - Style Proshow - styleproshow.org- Abstract Light
        Video HD
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Graphic - Web - eMarketing
purpose:
  - type: contact
    url: 'tel:+38763313588'
    label: Call +38763313588
  - type: contact
    url: 'mailto:gordan@connect.ba'
    label: Contact me
opengraph:
  type: 'https://www.facebook.com/Connect.Agencija.za.trzisne.komunikacije/'
