typography_spectrum: 0.9332921466045082
color:
  brandStrength: 0.3129659063882646
  lightness: 0.8891371711338917
  saturation: 0.24853577919885295
  rhythmicContrast: 0.846000962929044
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
github: true
layout_spectrum: 0.2108489132817318
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e298f4a-23fd-424d-85f3-ff25c48fa4c8.png
name: Agencija Connect
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Portfolio
    id: 57e6afcb-e469-49c7-9d3e-8457e96f582c
    type: content
  - name: Cjenik
    url: >-
      https://docs.google.com/forms/d/e/1FAIpQLScdOVsi3x4G0Lhj3_OM6jahpukJaGd1BQo7SdDcZ_cg58LITg/viewform
    type: external
  - name: Kontakt
    id: a50ff2fa-b95e-4687-b31c-a102b3e1e8e7
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d3c549c9-bef1-4fa3-a40e-b47af7508b69.png
title: Agencija Connect
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/9ee07b2254f91a8a9c2e53d72ffcec9258981239.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/9ee07b2254f91a8a9c2e53d72ffcec9258981239.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Graphic - Web - eMarketing
purpose:
  - type: contact
    url: 'tel:+38763313588'
    label: Call +38763313588
  - type: contact
    url: 'mailto:gordan@connect.ba'
    label: Contact me
