layout_spectrum: 0.43373169118400184
typography_spectrum: 0.483122686606712
color:
  lightness: 0.43013749425225695
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  saturation: 0.4709705278639783
  brandStrength: 0.509184106338382
  rhythmicContrast: 0.4798459875916527
coverPrefs:
  filter: false
content_rating:
  adult: false
github: true
opengraph:
  type: 'https://www.facebook.com/Connect.Agencija.za.trzisne.komunikacije/'
analytics:
  google: UA-19682937-18
author: {}
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e298f4a-23fd-424d-85f3-ff25c48fa4c8.png
name: Agencija Connect-Grafički i Web Dizajn-Internet oglašavanje
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Home
    url: 'http://connect365.online/'
    type: external
  - name: Što mi radimo
    url: 'http://connect365.online/sto-mi-radimo'
    type: external
  - name: Portfolio
    id: 57e6afcb-e469-49c7-9d3e-8457e96f582c
    type: content
  - name: Blog
    id: b48abd71-4d46-444d-a617-61cf471970ef
    type: content
  - name: Cjenik
    url: >-
      https://docs.google.com/forms/d/e/1FAIpQLScdOVsi3x4G0Lhj3_OM6jahpukJaGd1BQo7SdDcZ_cg58LITg/viewform
    type: external
  - name: Kontakt
    id: a50ff2fa-b95e-4687-b31c-a102b3e1e8e7
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d3c549c9-bef1-4fa3-a40e-b47af7508b69.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Grafički i Web Dizajn - Internet Marketing
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/0c94bbf9-9687-4ff2-8afc-f9bf39fd8b47.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/0c94bbf9-9687-4ff2-8afc-f9bf39fd8b47.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Kontaktirajte nas i unaprijediti ćemo vaše poslovanje
purpose:
  - type: contact
    url: 'tel:+38763313588'
    label: Call +38763313588
  - type: contact
    url: 'mailto:info@connect.ba'
    label: E-mail
